In [4]:
sent = ("휴일 인 오늘 도 서쪽 을 중심 으로 폭염 이 이어졌는데요, 내일 은 반가운 비소식 이 있습니다.",
        "폭염 을 피해서 휴일 에 놀러왔다가 갑작스런 비 로 인해 망연자실 하고 있습니다.") #띄어쓰기 위주로 구분하므로, 한글 문장의 조사를 띄어쓴 형태

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(sent) #문장 백터화 진행

print(tfidf_matrix.shape) #문장은 2개이며, 총 유니크 단어의 개수는 17개

(2, 17)


In [32]:
print(tfidf_matrix[0:1]) #첫번째 문장의 각 문장의 토큰의 tf-idf값

  (0, 16)	0.23061650387901597
  (0, 7)	0.3241234495558481
  (0, 6)	0.3241234495558481
  (0, 12)	0.3241234495558481
  (0, 8)	0.3241234495558481
  (0, 13)	0.23061650387901597
  (0, 9)	0.3241234495558481
  (0, 1)	0.3241234495558481
  (0, 4)	0.3241234495558481
  (0, 5)	0.3241234495558481
  (0, 11)	0.23061650387901597


In [43]:
from sklearn.metrics.pairwise import euclidean_distances

euclidean_distances(tfidf_matrix[0:1], tfidf_matrix)

# array([[0.        , 1.28099753]])

array([[0.        , 1.28099753]])

In [48]:
import numpy as np

# ∑_i x_i: L1
# sqrt(∑_i x_i): L2

def l1_normalize(v):
    norm = np.sum(v)
    return v / norm

def l2_normalize(v):
    norm = np.sqrt(np.sum(np.square(v)))
    return v / norm

tfidf_norm_l1 = l1_normalize(tfidf_matrix)
# tfidf_norm_l2 = l2_normalize(tfidf_matrix)

In [52]:
euclidean_distances(tfidf_norm_l1[0:1], tfidf_norm_l1[1:2])

# array([[0.20491229]])


array([[0.20491229]])

In [20]:
from sklearn.metrics.pairwise import cosine_similarity

# 코사인 유사도를 구해보자
cosine_similarity(tfidf_matrix[0:1], tfidf_matrix) ##tfidf_matrix[0:1]으로 첫번째 문장을 불러옴

# array([[1.        , 0.17952266]]) 자기 자신은 유사도가 1

array([[1.        , 0.17952266]])

In [59]:
#맨하탄 거리를 구해보자
from sklearn.metrics.pairwise import manhattan_distances

manhattan_distances(tfidf_norm_l1[0:1], tfidf_norm_l1[1:2])

# 최종 값: array([[0.77865927]])

array([[0.77865927]])