In [27]:
from sklearn.datasets import load_iris

In [28]:
iris_dataset = load_iris()

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(iris_dataset['data'], iris_dataset['target'], random_state=42)

In [30]:
from sklearn import cluster
k_means = cluster.KMeans(n_clusters=3) 

In [31]:
k_means.fit(X_train, Y_train)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=3, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [32]:
import numpy as np
X_new = np.array([[6.1, 2.8, 4.7, 1.2]])
X_new

array([[6.1, 2.8, 4.7, 1.2]])

In [33]:
prediction = k_means.predict(X_new)
prediction

array([0], dtype=int32)

In [34]:
iris_dataset.target_names[prediction]

array(['setosa'], dtype='<U10')

In [35]:
# 예측된 모델 평가하기
Y_pred = k_means.predict(X_test)
Y_pred

array([0, 1, 2, 0, 0, 1, 0, 2, 0, 0, 2, 1, 1, 1, 1, 0, 2, 0, 0, 2, 1, 0,
       1, 2, 2, 2, 2, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1], dtype=int32)

In [36]:
print('test accurate {:.2f}'.format(np.mean(Y_pred == Y_test)))

test accurate 0.26
