#  싸이킷-런 비지도 학습

In [1]:
from sklearn.datasets import load_iris

In [2]:
iris_dataset = load_iris()

In [3]:
from sklearn.model_selection import train_test_split
train_input, test_input, train_label, test_label = train_test_split(iris_dataset['data'], iris_dataset['target'], random_state=42)

# k-평균(k-means) 군집화

In [28]:
from sklearn import cluster
k_means = cluster.KMeans(n_clusters=3) 

In [29]:
k_means.fit(train_input, train_label)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=3, n_init=10, n_jobs=None, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [30]:
import numpy as np
new_input = np.array([[6.1, 2.8, 4.7, 1.2]])
new_input

array([[6.1, 2.8, 4.7, 1.2]])

In [31]:
prediction = k_means.predict(new_input)
prediction

array([0], dtype=int32)

In [32]:
iris_dataset.target_names[prediction]

array(['setosa'], dtype='<U10')

In [33]:
# 예측된 모델 평가하기
eval_label = k_means.predict(test_input)
eval_label

array([0, 1, 2, 0, 0, 1, 0, 2, 0, 0, 2, 1, 1, 1, 1, 0, 2, 0, 0, 2, 1, 0,
       1, 2, 2, 2, 2, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1], dtype=int32)

In [34]:
print('test accurate {:.2f}'.format(np.mean(eval_label == test_label)))

test accurate 0.26
